// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  header: string;
  modal: string;
  row: string;
  table: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
