// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  notificationActionButton: string;
}
export const cssExports: CssExports;
export default cssExports;
